server:
  port: 9995

management:
  port: 9995
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CLIENTE-APP
          uri: http://localhost:8083/
          predicates:
            - Path=/cliente/**
          filters:
            - RewritePath=/cliente/(?<path>.*), /$\{path}
        - id: PRODUTO-APP
          uri: http://localhost:8085/
          predicates:
            - Path=/produto/**
          filters:
            - RewritePath=/produto/(?<path>.*), /$\{path}
        - id: COMPRA-APP
          uri: http://localhost:8086/
          predicates:
            - Path=/compra/**
          filters:
            - RewritePath=/compra/(?<path>.*), /$\{path}
        - id: VALIDATOR-APP
          uri: http://localhost:8081/
          predicates:
            - Path=/validator/**
          filters:
            - RewritePath=/validator/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka