version: "3"
services:

  produto-app:
    image: api/produto:0.1
    container_name: produto-app
    ports:
      - "8085:8085"
    networks:
      - api-loja
    depends_on:
      - mongo-express
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: TAvtXVEzqqhUYGbH

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: TAvtXVEzqqhUYGbH

  mongo-express:
    image: mongo-express
    restart: always
    container_name: "mongo-express"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: TAvtXVEzqqhUYGbH
      ME_CONFIG_MONGODB_URL: mongodb+srv://Admin:TAvtXVEzqqhUYGbH@cluster0.q2toz.mongodb.net/?retryWrites=true&w=majority

  mysql_db:
    image: "mysql:8.0.23"
    container_name: "mysql_db"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - api-loja
    environment:
      MYSQL_DATABASE: loja
      MYSQL_ROOT_PASSWORD: root

  cliente-app:
    image: api/cliente:0.1
    container_name: cliente-app
    restart: on-failure
    ports:
      - "8083:8083"
    networks:
      - api-loja
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/loja?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC

volumes:
  mysql_db:
    driver: local

networks:
  api-loja:



