version: "3"
services:
  spring-app:
    image: api/produto:0.1
    container_name: app
    ports:
      - "8085:8085"
    networks:
      - api-loja
    depends_on:
      - mongo-express
      - mongodb
    environment:
      spring.data.mongo.db: mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: TAvtXVEzqqhUYGbH

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: TAvtXVEzqqhUYGbH
      ME_CONFIG_MONGODB_URL: mongodb+srv://Admin:TAvtXVEzqqhUYGbH@cluster0.q2toz.mongodb.net/test
networks:
  api-loja: