version: "3"
services:

  mysql_db:
    image: "mysql:8.0"
    container_name: "mysql_db"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - api-loja
    environment:
      MYSQL_DATABASE: loja
      MYSQL_ROOT_PASSWORD: root

  spring-app:
    image: api/cliente:0.1
    container_name: app
    restart: on-failure
    ports:
      - "8083:8083"
    networks:
      - api-loja
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/loja?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC


volumes:
  mysql_db:
    driver: local
networks:
  api-loja: